//! `velme.lock` (`runtime/32` §5, D-12): which artifact each goal uses.

use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use velme_diagnostics::{Code, Diagnostic, Span};
use velme_ir::Fingerprint;

use crate::store::{TMP_DIR, VELME_DIR, sync_dir, write_temp};

/// The lock's file name, in the project root (`runtime/32` §4).
pub const LOCK_FILE: &str = "velme.lock";

/// The lock format this build reads and writes.
pub const LOCK_VERSION: i64 = 1;

/// The first line of every lock file (`runtime/32` §5).
const HEADER: &str = "# Generated by `velme build`. Commit this file. Do not edit by hand.";

/// The pins of one project (`runtime/32` §5): one entry per goal, sorted by (`file`, `name`) (R-ART-13).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lock {
    /// The language version the pinned goals were built from.
    pub language: String,
    entries: Vec<Entry>,
}

/// The pin of one goal (`runtime/32` §5). Its keys are what the goal was built from; an entry whose keys differ from
/// the ones computed from current source is stale (R-ART-14).
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Entry {
    /// The source file declaring the goal, project-relative with `/` separators (`tooling/40` R-CLI-19).
    pub file: String,
    /// The goal's name.
    pub name: String,
    /// The goal's signature.
    pub signature: Fingerprint,
    /// The goal's `contract_key`.
    pub contract_key: Fingerprint,
    /// The artifact the goal uses.
    pub artifact: Fingerprint,
}

/// The format version alone, read first so a lock of another format is named as such rather than by the fields it
/// has that this one doesn't.
#[derive(Deserialize)]
struct Format {
    version: i64,
}

/// The file as written.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Document {
    // Checked through [`Format`]; listed so it isn't an unknown field.
    #[serde(rename = "version")]
    _version: i64,
    language: String,
    #[serde(default)]
    goal: Vec<Entry>,
}

impl Lock {
    /// A lock with no entries, for source of language `language`.
    pub fn new(language: impl Into<String>) -> Self {
        Lock {
            language: language.into(),
            entries: Vec::new(),
        }
    }

    /// Where the lock of the project whose root is `project` is: `<project>/velme.lock`.
    pub fn path(project: &Path) -> PathBuf {
        project.join(LOCK_FILE)
    }

    /// Reads the lock of `project`; `None` if it has none.
    pub fn read(project: &Path) -> Result<Option<Lock>, LockError> {
        match fs::read(Lock::path(project)) {
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(LockError::Unreadable { error }),
            Ok(bytes) => {
                let text = String::from_utf8(bytes).map_err(|e| LockError::Malformed { reason: e.to_string() })?;
                Lock::parse(&text).map(Some)
            }
        }
    }

    /// Reads lock text. Entries may come in any order, but each goal at most once.
    pub fn parse(text: &str) -> Result<Lock, LockError> {
        let malformed = |e: toml::de::Error| LockError::Malformed {
            reason: e.message().to_owned(),
        };
        let format: Format = toml::from_str(text).map_err(malformed)?;
        if format.version != LOCK_VERSION {
            return Err(LockError::Format { found: format.version });
        }
        let document: Document = toml::from_str(text).map_err(malformed)?;
        let mut entries = document.goal;
        entries.sort_by(|a, b| key(a).cmp(&key(b)));
        if let Some(pair) = entries
            .windows(2)
            .find(|pair| matches!(pair, [a, b] if key(a) == key(b)))
        {
            let name = pair.first().map_or("", |e| e.name.as_str());
            return Err(LockError::Malformed {
                reason: format!("it pins the goal `{name}` twice"),
            });
        }
        Ok(Lock {
            language: document.language,
            entries,
        })
    }

    /// The lock as text: the same entries always give the same bytes, so an unchanged build leaves no diff (R-ART-13).
    pub fn to_text(&self) -> String {
        let mut out = format!(
            "{HEADER}\nversion  = {LOCK_VERSION}\nlanguage = {}\n",
            quoted(&self.language)
        );
        for entry in &self.entries {
            out.push_str(&format!(
                "\n[[goal]]\nfile          = {}\nname          = {}\nsignature     = \"{}\"\n\
                 contract_key  = \"{}\"\nartifact      = \"{}\"\n",
                quoted(&entry.file),
                quoted(&entry.name),
                entry.signature,
                entry.contract_key,
                entry.artifact,
            ));
        }
        out
    }

    /// Writes the lock of `project`, replacing it whole: through a temporary file under `.velme/tmp/`, so a crash
    /// leaves either the old lock or the new one. A lock with the same bytes is left untouched.
    pub fn write(&self, project: &Path) -> io::Result<()> {
        let text = self.to_text();
        let path = Lock::path(project);
        match fs::read(&path) {
            Ok(old) if old == text.as_bytes() => return Ok(()),
            Err(e) if e.kind() != io::ErrorKind::NotFound => return Err(e),
            _ => {}
        }
        let tmp = project.join(VELME_DIR).join(TMP_DIR);
        fs::create_dir_all(&tmp)?;
        let temp = write_temp(&tmp, LOCK_FILE, text.as_bytes())?;
        if let Err(e) = fs::rename(&temp, &path) {
            let _ = fs::remove_file(&temp);
            return Err(e);
        }
        sync_dir(project)
    }

    /// The entries, sorted by (`file`, `name`).
    pub fn entries(&self) -> &[Entry] {
        &self.entries
    }

    /// The entry of the goal `name` declared in `file`.
    pub fn entry(&self, file: &str, name: &str) -> Option<&Entry> {
        self.entries
            .binary_search_by(|e| key(e).cmp(&(file, name)))
            .ok()
            .and_then(|i| self.entries.get(i))
    }

    /// Pins `entry`, replacing the goal's earlier entry if it has one.
    pub fn insert(&mut self, entry: Entry) {
        match self.entries.binary_search_by(|e| key(e).cmp(&key(&entry))) {
            Ok(i) => {
                if let Some(slot) = self.entries.get_mut(i) {
                    *slot = entry;
                }
            }
            Err(i) => self.entries.insert(i, entry),
        }
    }
}

/// The order of entries (R-ART-13).
fn key(entry: &Entry) -> (&str, &str) {
    (&entry.file, &entry.name)
}

/// `text` as a TOML string.
fn quoted(text: &str) -> String {
    toml::Value::String(text.to_owned()).to_string()
}

/// What to do about a lock this build can't read but could have written.
fn restore_help() -> String {
    format!("`velme build` writes `{LOCK_FILE}`; restore it from version control")
}

/// Why a project's lock could not be read.
#[derive(Debug)]
pub enum LockError {
    /// The file is there but could not be read.
    Unreadable {
        /// Why.
        error: io::Error,
    },
    /// The file is a lock of another format.
    Format {
        /// Its `version`.
        found: i64,
    },
    /// The file is not a lock this build reads.
    Malformed {
        /// What is wrong with it.
        reason: String,
    },
}

impl LockError {
    /// The diagnostic code: the lock is a file Velme couldn't read, `VL0901`.
    pub fn code(&self) -> Code {
        Code::FileError
    }

    /// The failure, worded as in `reference/90`. It belongs to the project, not to a place in the source (D-72).
    pub fn diagnostic(&self) -> Diagnostic {
        let diag = Diagnostic::new(self.code(), Span::default(), format!("I couldn't open `{LOCK_FILE}`."));
        match self {
            Self::Unreadable { error } => diag.with_note(error.to_string()),
            Self::Format { found } => {
                let diag = diag.with_note(format!(
                    "it is lock format {found}, but this version of Velme reads format {LOCK_VERSION}"
                ));
                if *found > LOCK_VERSION {
                    diag.with_help("it was written by a newer Velme: upgrade Velme to use it")
                } else {
                    diag.with_help(restore_help())
                }
            }
            Self::Malformed { reason } => diag.with_note(reason.clone()).with_help(restore_help()),
        }
    }
}

impl fmt::Display for LockError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unreadable { error } => write!(f, "`{LOCK_FILE}` could not be read: {error}"),
            Self::Format { found } => write!(f, "`{LOCK_FILE}` is lock format {found}, not {LOCK_VERSION}"),
            Self::Malformed { reason } => write!(f, "`{LOCK_FILE}` is not a lock file: {reason}"),
        }
    }
}

impl std::error::Error for LockError {}
