[package]
name = "velme-cli"
description = "The `velme` command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "velme"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
velme-diagnostics.workspace = true
velme-sema.workspace = true
velme-syntax.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
