[package]
name = "thela-cli"
description = "The `thela` command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "thela"
path = "src/main.rs"

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
